/**
 * Elite Email Template Wrapper — v5 (Pure String Engine)
 *
 * ROOT CAUSE FIX: The previous DOMParser approach had a fundamental bug —
 * iterating a static snapshot of childNodes while mutating the live DOM
 * caused nodes to be skipped or double-processed, so emoji-only <p> tags
 * were NEVER actually merged into their neighbors.
 *
 * v5 uses 100% pure string manipulation (no DOM, no mutation side-effects).
 * It parses the <p>...</p> blocks as strings, merges emoji-only blocks into
 * their neighboring blocks, then reassembles. Bulletproof.
 */

// ─────────────────────────────────────────────────────────────────────────────
// SANITIZE HTML — TipTap Engine
// ─────────────────────────────────────────────────────────────────────────────
// TipTap generates clean, semantic HTML natively. We only need basic inline
// styles to ensure consistent rendering across email clients (like Outlook).

/**
 * flattenHtml — Fixes malformed HTML generated by TipTap editor.
 * When users switch between Visual and Raw Code tabs, TipTap can
 * wrap content in redundant nested <p><p><p>...</p></p></p> structures.
 * Email clients auto-close nested <p> tags, creating blank lines.
 * This function MUST run before any other sanitization.
 */
export function flattenHtml(raw) {
    if (!raw) return '';
    let s = raw;

    // 1. Flatten nested <p> tags: <p><p>content</p></p> → <p>content</p>
    let prev = '';
    while (s !== prev) {
        prev = s;
        s = s.replace(/<p([^>]*)>\s*<p/gi, '<p');
        s = s.replace(/<\/p>\s*<\/p>/gi, '</p>');
    }

    // 2. Collapse excessive consecutive <br> tags into one
    s = s.replace(/(<br\s*\/?\s*>[\s\n]*){2,}/gi, '<br>');

    return s.trim();
}

export function cleanHtmlForEmail(raw) {
    if (!raw) return '';

    // STEP 0: Flatten nested/malformed HTML from TipTap editor
    let s = flattenHtml(raw);

    // STEP 0.5: Force empty paragraphs to have a <br> so email clients do not collapse them
    s = s.replace(/<p([^>]*)>\s*<\/p>/gi, '<p$1><br></p>');

    // STEP 1: Merge lone-emoji paragraphs with the next/previous paragraph.
    let prev = '';
    while (s !== prev) {
        prev = s;
        
        // Match 2 consecutive paragraphs
        s = s.replace(/<p([^>]*)>([\s\S]*?)<\/p>[\s\n]*(?:<br\s*\/?>)?[\s\n]*<p([^>]*)>([\s\S]*?)<\/p>/gi, (match, a1, c1, a2, c2) => {
            const strip1 = c1.replace(/<[^>]+>/g, '').replace(/&[a-zA-Z0-9#]+;/g, '').trim();
            const isEmoji1 = (strip1.length > 0 && strip1.length <= 10 && !/[a-zA-Z0-9]/.test(strip1));

            const strip2 = c2.replace(/<[^>]+>/g, '').replace(/&[a-zA-Z0-9#]+;/g, '').trim();
            const isEmoji2 = (strip2.length > 0 && strip2.length <= 10 && !/[a-zA-Z0-9]/.test(strip2));

            // Merge backwards: Para 2 is emoji -> append to Para 1
            if (isEmoji2 && !isEmoji1) {
                return `<p${a1}>${c1} ${c2}</p>`;
            }
            // Merge forwards: Para 1 is emoji -> prepend to Para 2
            if (isEmoji1 && !isEmoji2) {
                return `<p${a2}>${c1} ${c2}</p>`;
            }
            // Both emojis -> merge forward
            if (isEmoji1 && isEmoji2) {
                return `<p${a2}>${c1} ${c2}</p>`;
            }
            return match;
        });
    }

    // STEP 2: Remove <br> immediately after a short non-ASCII token (emoji) in the same block
    s = s.replace(/(<[^>]*>)?(?:&nbsp;|\s)*([^\s<a-zA-Z0-9&;#>="']{1,8})(?:&nbsp;|\s)*<br\s*\/?>[\s\n]*/gi, (match, tag, chars) => {
        return (tag || '') + chars + ' ';
    });

    // STEP 3: Apply uniform standard margins for all email clients.
    s = s.replace(/<p>/gi, '<p style="margin: 0 0 14px 0;">');
    s = s.replace(/style="margin: 0 0 14px 0;" style="margin: 0 0 14px 0;"/gi, 'style="margin: 0 0 14px 0;"');

    // STEP 4: Normalize bold tags for email client safety
    s = s.replace(/<b>/gi, '<strong>').replace(/<\/b>/gi, '</strong>');

    return s;
}

// Export named sanitizeQuillHtml for backward compatibility
export const sanitizeQuillHtml = cleanHtmlForEmail;


// ─────────────────────────────────────────────────────────────────────────────
// WRAP EMAIL TEMPLATE
// Full HTML email wrapper (card-based, responsive, brand-focused)
// ─────────────────────────────────────────────────────────────────────────────

export function wrapEmailTemplate({
    body,
    agencyName = 'QuipuReservas',
    agencyUrl = '',
    agencyEmail = '',
    agencyPhone = '',
    logoUrl = '',
    previewText = '',
    primaryColor = '#1a73e8',
    year = new Date().getFullYear()
}) {
    const safeBody = sanitizeQuillHtml(body);

    const displayPreview = previewText || `${agencyName} — Información importante para tu viaje`;

    // Sanitize Logo URL
    let safeLogoUrl = '';
    if (logoUrl && typeof logoUrl === 'string' && logoUrl.trim().length > 4) {
        const trimmed = logoUrl.trim();
        if (trimmed.startsWith('http') || trimmed.match(/\.(jpeg|jpg|gif|png|webp|svg)/i)) {
            safeLogoUrl = trimmed.startsWith('http') ? trimmed : `https://${trimmed.replace(/^\/+/, '')}`;
        }
    }

    // Preheader hack: push main body out of email snippet
    const preheaderHack = '&zwnj;&nbsp;'.repeat(100);

    return `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="es" xml:lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="x-apple-disable-message-reformatting" />
    <meta name="google" content="notranslate" />
    <meta name="format-detection" content="telephone=no" />
    <title>${agencyName}</title>
    <!--[if mso]>
    <xml>
        <o:OfficeDocumentSettings><o:AllowPNG/><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings>
    </xml>
    <![endif]-->
    <style type="text/css">
        body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
        table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
        img { -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; display: block; }
        body { margin: 0; padding: 0; width: 100% !important; height: 100% !important; background-color: #f0f2f5; }
        .card { border-radius: 16px; overflow: hidden; box-shadow: 0 4px 25px rgba(0,0,0,0.05); }
        p { margin-top: 0; margin-bottom: 2px; }
        ul, ol { margin-top: 3px; margin-bottom: 8px; padding-left: 18px; }
        li { margin-bottom: 4px; }
        @media only screen and (max-width: 600px) {
            .container { width: 100% !important; padding: 10px !important; }
            .content-padding { padding: 24px 20px !important; }
        }
    </style>
</head>
<body class="notranslate" translate="no" style="margin:0; padding:0; background-color:#f0f2f5; font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">

    <!-- Hidden Preheader -->
    <div style="display:none; font-size:1px; color:#f0f2f5; line-height:1px; max-height:0px; max-width:0px; opacity:0; overflow:hidden;">
        ${displayPreview}
        ${preheaderHack}
    </div>

    <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td align="center" style="padding: 40px 10px;">
                <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="600" class="container" style="width:100%; max-width:600px;">
                    
                    <!-- Main Card -->
                    <tr>
                        <td class="card" style="background-color: #ffffff; border: 1px solid #e1e4e8; border-radius: 16px; overflow: hidden;">
                            <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
                                <!-- Black Header Banner -->
                                <tr>
                                    <td align="center" style="background-color: #000000; border-radius: 16px 16px 0 0; padding: 28px 20px; mso-padding-alt: 28px 20px;">
                                        <!--[if mso]><table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%"><tr><td align="center" bgcolor="#000000" style="background-color:#000000;"><![endif]-->
                                        ${safeLogoUrl
                                            ? `<img src="${safeLogoUrl}" alt="${agencyName}" width="220" style="max-width: 220px; height: auto; display: block; border: 0; margin: 0 auto;" />`
                                            : `<h1 style="margin:0; color:#ffffff; font-size:26px; font-weight:800; letter-spacing:-0.03em; font-family:'Segoe UI', Roboto, sans-serif;">${agencyName}</h1>`
                                        }
                                        <!--[if mso]></td></tr></table><![endif]-->
                                    </td>
                                </tr>
                                <!-- Body Content -->
                                <tr>
                                    <td class="content-padding" style="padding: 40px 40px 30px 40px;">
                                        <div style="font-size: 16px; line-height: 1.5; color: #3c4043; font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
                                            ${safeBody}
                                        </div>
                                    </td>
                                </tr>
                                <!-- Divider -->
                                <tr>
                                    <td style="padding: 0 40px;">
                                        <hr style="border: 0; border-top: 1px dashed #e2e8f0; margin: 0;" />
                                    </td>
                                </tr>
                                <!-- Footer Brand Info -->
                                <tr>
                                    <td class="content-padding" style="padding: 24px 40px 32px 40px;">
                                        <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
                                            <tr>
                                                <td style="font-family: inherit; font-size: 13px; color: #70757a; line-height: 1.5;">
                                                    <strong style="color: #202124;">${agencyName}</strong><br />
                                                    ${agencyUrl ? `<a href="${agencyUrl}" style="color: ${primaryColor}; text-decoration: none; font-weight: 600;">${agencyUrl.replace(/^https?:\/\//, '')}</a>` : ''}
                                                    ${agencyPhone ? `<br />WhatsApp: ${agencyPhone}` : ''}
                                                </td>
                                                <td align="right" style="vertical-align: bottom;">
                                                     <span style="font-size: 11px; color: #dadce0;">&copy; ${year}</span>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <!-- Legal / Unsubscribe -->
                    <tr>
                        <td align="center" style="padding: 24px 40px; color: #9aa0a6; font-size: 11px; line-height: 1.5;">
                            Este es un mensaje automático enviado por ${agencyName}.<br />
                            Si no deseas recibir más correos, por favor contáctanos a <a href="mailto:${agencyEmail || 'soporte@tuagencia.com'}" style="color: #9aa0a6;">${agencyEmail || 'soporte@tuagencia.com'}</a>.
                        </td>
                    </tr>

                </table>
            </td>
        </tr>
    </table>
</body>
</html>`;
}
